### ISSUE TITLE
Building tdlib with msys/mignw

### ISSUE THREAD

**Issue by leeroy-Jk** [dancojocaru2000/dart_tdlib_types#1]
Hello, I saw your issue in the tdlib repo https://github.com/tdlib/td/issues/1429
I have the same problem now and I would like to find out your resulted solving about.

**Comment by dancojocaru2000** [comment]
Sadly, I haven't managed to figure out how. Sorry.

**Comment by leeroy-Jk** [comment]
It's sad, but thanks for the answer :-)

**Comment by MLXProjects** [comment]
I was able to build tdlib for win32 using msys2, just installing gcc and cmake packages.
Didn't try linking it, but it should work :P
PD: I used msys2 shell, not the mingw64 one

**Comment by leeroy-Jk** [comment]
> I was able to build tdlib for win32 using msys2, just installing gcc and cmake packages. Didn't try linking it, but it should work :P PD: I used msys2 shell, not the mingw64 one

Yeah, I made the same, but I compiled via mingw64 console app. But the linking process is so slow. At the Unix-like it passed far faster :)
